IIS/config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :path => 'u', :controllers => { :registrations => "user/registrations" }
  resources :users
  resources :reservations do
    delete 'processReservation/:id' => 'reservations#processReservation', as: :processReservation
  end
  resources :suppliers
  resources :insurers
  resources :drugs
  resources :branches
  resources :sales
  resources :orders do
    post 'processOrder/:id' => 'orders#processOrder', as: :processOrder
    post 'deprocessOrder/:id' => 'orders#deprocessOrder', as: :deprocessOrder
  end
  
  root to: redirect('/drugs')
end

IIS/app/models/supplier.rb
class Supplier < ApplicationRecord
    has_many :drugs, inverse_of: :supplier
end

IIS/app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_supplier, only: [:show, :edit, :update, :destroy]

  # GET /suppliers
  # GET /suppliers.json
  def index
    authorize Supplier
    @suppliers = Supplier.order(:name).page params[:page]
  end

  # GET /suppliers/1
  # GET /suppliers/1.json
  def show
    authorize Supplier
  end

  # GET /suppliers/new
  def new
    authorize Supplier
    @supplier = Supplier.new
  end

  # GET /suppliers/1/edit
  def edit
    authorize Supplier
  end

  # POST /suppliers
  # POST /suppliers.json
  def create
    authorize Supplier
    @supplier = Supplier.new(supplier_params)

    respond_to do |format|
      if @supplier.save
        format.html { redirect_to suppliers_url, notice: 'Dodavatel byla úspěšně přidán.' }
        format.json { render :show, status: :created, location: @supplier }
      else
        format.html { render :new }
        format.json { render json: @supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /suppliers/1
  # PATCH/PUT /suppliers/1.json
  def update
    authorize Supplier
    respond_to do |format|
      if @supplier.update(supplier_params)
        format.html { redirect_to suppliers_url, notice: 'Dodavatel byla úspěšně upraven.' }
        format.json { render :show, status: :ok, location: @supplier }
      else
        format.html { render :edit }
        format.json { render json: @supplier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /suppliers/1
  # DELETE /suppliers/1.json
  def destroy
    authorize Supplier
    @supplier.destroy
    respond_to do |format|
      format.html { redirect_to suppliers_url, notice: 'Dodavatel byla úspěšně smazán.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_supplier
      @supplier = Supplier.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def supplier_params
      params.require(:supplier).permit(:name)
    end
end

IIS/app/helpers/suppliers_helper.rb
module SuppliersHelper
end

IIS/app/views/suppliers/_form.html.erb
<%= simple_form_for(@supplier) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  	<%= f.input :name, label: 'Jméno', required: true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, value: "Potvrdit" %>
  </div>
<% end %>

IIS/app/views/suppliers/edit.html.erb
<h1>Úprava dodavatele</h1>

<%= render 'form', supplier: @supplier %>

<%= link_to 'Zpět', suppliers_path %>

IIS/app/views/suppliers/index.html.erb
<h1>Dodavatelé</h1>
<div class="table-responsive well">
  <table class="table">
    <thead>
      <tr>
        <th>Název</th>  
        <th class='text-center'>Detail</th>
        <th class='text-center'>Upravit</th>
        <th class='text-center'>Smazat</th>
      </tr>
    </thead>

    <tbody>
      <% @suppliers.each do |supplier| %>
        <tr>
          <td><%= supplier.name %></td>
          <td class='text-center'><%= link_to "<span class='glyphicon glyphicon-eye-open'> </span>".html_safe, supplier %></td>
          <td class='text-center'><%= link_to "<span class='glyphicon glyphicon-pencil'> </span>".html_safe, edit_supplier_path(supplier) %></td>
          <td class='text-center'><%= link_to "<span class='glyphicon glyphicon-remove-sign'> </span>".html_safe, supplier, method: :delete, data: { confirm: 'Jste si jisti?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
    <%= paginate @suppliers %>
  
</div>

<br>

<%= button_to 'Nový dodavatel', new_supplier_path, method: :get  %>

IIS/app/views/suppliers/new.html.erb
<h1>Nový dodavatel</h1>

<%= render 'form', supplier: @supplier %>

<%= link_to 'Zpět', suppliers_path %>

IIS/app/views/suppliers/show.html.erb
<h1>Seznam dodávaných léků</h1>
<h3><%= @supplier.name %></h3>
<div class="table-responsive well">
  <table class="table">
    <thead>
      <tr>
        <th>Název léku</th>
        <th>Cena</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
	    <% @supplier.drugs.each do |drug| %>
	        <tr>
	          <td><%= drug.name %></td>
            <td><%= drug.bprice %> Kč</td>
	        </tr>
	      <% end %>
    </tbody>
  </table>
</div>


<%= link_to 'Upravit', edit_supplier_path(@supplier) %> |
<%= link_to 'Zpět', suppliers_path %>