IIS/config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :path => 'u', :controllers => { :registrations => "user/registrations" }
  resources :users
  resources :reservations do
    delete 'processReservation/:id' => 'reservations#processReservation', as: :processReservation
  end
  resources :suppliers
  resources :insurers
  resources :drugs
  resources :branches
  resources :sales
  resources :orders do
    post 'processOrder/:id' => 'orders#processOrder', as: :processOrder
    post 'deprocessOrder/:id' => 'orders#deprocessOrder', as: :deprocessOrder
  end
  
  root to: redirect('/drugs')
end

IIS/app/models/reservation.rb
class Reservation < ApplicationRecord
	belongs_to :branch
    has_many :reservation_drugs, inverse_of: :reservation
    has_many :drugs, -> { uniq }, :through => :reservation_drugs
    validates_presence_of :reservation_drugs, :message => "Prosím zadejte alespoň jeden lék"

    accepts_nested_attributes_for :reservation_drugs, reject_if: :all_blank, allow_destroy: true

    filterrific(
        default_filter_params: {},
        available_filters: [
          :search_query
        ]
      )
    
      scope :search_query, lambda { |query|
        return nil  if query.blank?
        where('LOWER(reservations.customer) LIKE ?', "%#{query.downcase}%")
      }
end

IIS/app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_reservation, only: [:show, :edit, :update, :destroy, :processReservation]

  # GET /reservations
  # GET /reservations.json
  def index
    @filterrific = initialize_filterrific(
      Reservation,
      params[:filterrific],
      select_options: {
      }
    ) or return

    @reservations = @filterrific.find.page(params[:page])

    respond_to do |format|
      format.html
      format.js
    end

    rescue ActiveRecord::RecordNotFound => e
      # There is an issue with the persisted param_set. Reset it.
      redirect_to(reset_filterrific_url(format: :html)) and return
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    authorize Reservation
    @reservation = Reservation.new
    @reservation.reservation_drugs.build 
  end

  # GET /reservations/1/edit
  def edit
    authorize Reservation
  end

  # POST /reservations
  # POST /reservations.json
  def create
    authorize Reservation
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Rezervace byla úspěšně evidována.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    authorize Reservation
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Rezervace byla úspěšně upravena.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    authorize Reservation
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Rezervace byla úspěšně zrušena.' }
      format.json { head :no_content }
    end
  end

  def processReservation
    authorize Reservation
    @reservation.destroy
    redirect_to new_sale_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reservation_params
      params.require(:reservation).permit(:id, :branch_id,:customer, :date, reservation_drugs_attributes: [:id, :reservation_id, :drug_id, :amount, :_destroy])
    end
end

IIS/app/helpers/reservations_helper.rb
module ReservationsHelper
end

IIS/app/views/reservations/_form.html.erb
<%= simple_form_for(@reservation) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  	<%= f.input :customer, label: 'Jméno zákazníka', required: true %>
  	<%= f.input :date, label: 'Očekávané datum vyzvednutí', required: true %>
    <%= f.association :branch, label: 'Pobočka', collection: Branch.all.order(:address), label_method: :address, prompt: "Zvolte pobočku", required: true %>
  </div>

  <div id="reservation_drugs">
      <%= f.simple_fields_for :reservation_drugs do |reservation_drug| %>
        <%= render 'reservation_drug_fields', f: reservation_drug%>
      <% end %>
      <div class="links">
        <%= link_to_add_association 'Přidat lék', f, :reservation_drugs, :class => 'btn btn-default' %>
      </div>
    </div>

  <div class="form-actions">
    <%= f.button :submit, value: "Potvrdit" %>
  </div>
<% end %>

IIS/app/views/reservations/_list.html.erb
<div class="table-responsive well" id="filterrific_results">
    <table class="table">
      <thead>
        <tr>
          <th>Zákazník</th>
          <th class='text-center'>Datum vyzvednutí</th>
          <th class='text-center'>Vyřídit rezervaci</th>
          <th class='text-center'>Detail</th>
          <th class='text-center'>Upravit</th>
          <th class='text-center'>Smazat</th>
        </tr>
      </thead>
  
      <tbody>
        <% @reservations.each do |reservation| %>
          <tr>
            <td><%= reservation.customer %></td>
            <td class='text-center'><%= reservation.date.strftime("%d.%m. %Y") %></td>
            <td class='text-center'><%= link_to "<span class='glyphicon glyphicon-list-alt'> </span>".html_safe, "/reservations/#{ reservation.id }/processReservation/#{ reservation.id }", method: :delete, data: { confirm: 'Jste si jisti?' } %></td>
            <td class='text-center'><%= link_to "<span class='glyphicon glyphicon-eye-open'> </span>".html_safe, reservation %></td>
            <td class='text-center'><%= link_to "<span class='glyphicon glyphicon-pencil'> </span>".html_safe, edit_reservation_path(reservation) %></td>
            <td class='text-center'><%= link_to "<span class='glyphicon glyphicon-remove-sign'> </span>".html_safe, reservation, method: :delete, data: { confirm: 'Jste si jisti?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    
      <%= paginate @reservations %>
    
  </div>

IIS/app/views/reservations/_reservation_drug_fields.html.erb
<div class="nested-fields">
        <%= f.input :drug_id, label: 'Lék', collection: Drug.all.order(:name), prompt: "Vyberte lék", required: true%>
        <%= f.input :amount, label: 'Kusů', required: true%>
        <%= link_to_remove_association "Odebrat Lék", f %>
</div>

IIS/app/views/reservations/edit.html.erb
<h1>Úprava rezervace</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Zpět', reservations_path %>

IIS/app/views/reservations/index.html.erb
<h1>Rezervace</h1>

<%= form_for_filterrific @filterrific, :remote => true do |f| %>
<div>
  Vyhledat zákazníka:
  <%# give the search field the 'filterrific-periodically-observed' class for live updates %>
  <%= f.text_field(
    :search_query,
    class: 'filterrific-periodically-observed'
  ) %>
  <%= link_to(
    'Zrušit filtr',
    reset_filterrific_url,
  ) %>
</div>

<br>
 
<%# add an automated spinner to your form when the list is refreshed %>
<%= render_filterrific_spinner %>
<% end %>

<%= render(
partial: 'reservations/list',
locals: { reservations: @reservations }
) %>

<br>

<%= button_to 'Nová rezervace', new_reservation_path, method: :get  %>

IIS/app/views/reservations/index.js.erb
<% js = escape_javascript(
    render(partial: 'reservations/list', locals: { reservations: @reservations })
  ) %>
  $("#filterrific_results").html("<%= js %>");

IIS/app/views/reservations/new.html.erb
<h1>Nová rezervace</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Zpět', reservations_path %>

IIS/app/views/reservations/show.html.erb
<h3><%= @reservation.customer %> - <%= @reservation.date.strftime("%d.%m. %Y") %></h3>

<div class="table-responsive well">
	<table class="table">
	    <thead>
	      <tr>
	        <th>Název léku</th>
	        <th>Množství</th>
	      </tr>
	    </thead>
	    <tbody>
	      <% @reservation.reservation_drugs.each do |reservation| %>
	        <tr>
	        	<td><%= reservation.drug.name %></td>
	        	<td><%= reservation.amount %></td>
	        </tr>
	      <% end %>
	    </tbody>
    </table>
</div>
<%= link_to 'Upravit', edit_reservation_path(@reservation) %> |
<%= link_to 'Zpět', reservations_path %>