IIS/config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :path => 'u', :controllers => { :registrations => "user/registrations" }
  resources :users
  resources :reservations do
    delete 'processReservation/:id' => 'reservations#processReservation', as: :processReservation
  end
  resources :suppliers
  resources :insurers
  resources :drugs
  resources :branches
  resources :sales
  resources :orders do
    post 'processOrder/:id' => 'orders#processOrder', as: :processOrder
    post 'deprocessOrder/:id' => 'orders#deprocessOrder', as: :deprocessOrder
  end
  
  root to: redirect('/drugs')
end

IIS/app/models/branch.rb
class Branch < ApplicationRecord
	has_many :reservations, dependent: :destroy, inverse_of: :branch
	has_many :orders, dependent: :destroy, inverse_of: :branch
    has_many :availables, dependent: :destroy, inverse_of: :branch
    has_many :drugs, -> { uniq }, :through => :availables

    has_many :users
end

IIS/app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_branch, only: [:show, :edit, :update, :destroy]

  # GET /branches
  # GET /branches.json
  def index
    authorize Branch
    @branches = Branch.order(:address).page params[:page]
  end

  # GET /branches/1
  # GET /branches/1.json
  def show
    authorize Branch
    @users = User.where('branch_id = ?', @branch.id).page params[:page]
  end

  # GET /branches/new
  def new
    authorize Branch
    @branch = Branch.new
  end

  # GET /branches/1/edit
  def edit
    authorize Branch
  end

  # POST /branches
  # POST /branches.json
  def create
    authorize Branch
    @branch = Branch.new(branch_params)

    respond_to do |format|
      if @branch.save
        format.html { redirect_to branches_url, notice: 'Pobočka úspěšně vytvořena.' }
        format.json { render :show, status: :created, location: @branch }
      else
        format.html { render :new }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /branches/1
  # PATCH/PUT /branches/1.json
  def update
    authorize Branch
    respond_to do |format|
      if @branch.update(branch_params)
        format.html { redirect_to branches_url, notice: 'Pobočka úspěšně upravena.' }
        format.json { render :show, status: :ok, location: @branch }
      else
        format.html { render :edit }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /branches/1
  # DELETE /branches/1.json
  def destroy
    authorize Branch
    @branch.destroy
    respond_to do |format|
      format.html { redirect_to branches_url, notice: 'Pobočka úspěšně smazána.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_branch
      @branch = Branch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def branch_params
      params.require(:branch).permit(:address)
    end
end

IIS/app/helpers/branches_helper.rb
module BranchesHelper
end

IIS/app/views/branches/_form.html.erb
<%= simple_form_for(@branch) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :address, label: 'Adresa', required: true %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, value: "Potvrdit" %>
  </div>
<% end %>

IIS/app/views/branches/edit.html.erb
<h1>Editing Branch</h1>

<%= render 'form', branch: @branch %>

<%= link_to 'Show', @branch %> |
<%= link_to 'Back', branches_path %>

IIS/app/views/branches/index.html.erb
<h1>Pobočky</h1>
<div class="table-responsive well">
  <table class="table">
    <thead>
      <tr>
        <th>Adresa</th>
        <th class='text-center'>Seznam zaměstnanců</th>
        <th class='text-center'>Upravit adresu</th>
        <th class='text-center'>Smazat pobočku</th>
      </tr>
    </thead>

    <tbody>
      <% @branches.each do |branch| %>
        <tr>
          <td><%= branch.address %></td>
          <td class='text-center'><%= link_to "<span class='glyphicon glyphicon-eye-open'> </span>".html_safe, branch %></td>
          <td class='text-center'><%= link_to "<span class='glyphicon glyphicon-pencil'> </span>".html_safe, edit_branch_path(branch) %></td>
          <td class='text-center'><%= link_to "<span class='glyphicon glyphicon-remove-sign'> </span>".html_safe, branch, method: :delete, data: { confirm: 'Jste si jisti?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
    <%= paginate @branches %>
  
</div>

<br>

<%= button_to 'Přidat pobočku', new_branch_path, method: :get  %>

IIS/app/views/branches/new.html.erb
<h1>Nová pobočka</h1>
<%= render 'form', branch: @branch %>

<%= link_to 'Zpět', branches_path %>

IIS/app/views/branches/show.html.erb
<h1>Seznam zaměstnanců - <%= @branch.address %></h1>
<div class="table-responsive well">
    <table class="table">
      <thead>
        <tr>
          <th>Jméno</th>
          <th>Email</th>
          <th>Role</th>
        </tr>
      </thead>
  
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
            <td><%= user.role %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  
    <%= paginate @users %>
  
  </div>